---

- name: Config private network
  hosts: all
  remote_user: root
  serial: 1

  roles:
    - bridge
    - tinc

  post_tasks:
    - name: Restart tinc service
      tags: tinc
      ansible.builtin.systemd:
        name: tinc@{{ vpn_name }}
        state: restarted
      delegate_to: "{{ item }}"
      loop: "{{ groups['server'] }}"
