--- 

- name: Make sure /etc/nftables.d exists
  file:
    path: /etc/nftables.d 
    state: directory
    mode: '0755'

- name: Set iface_pub fact
  set_fact:
    iface_pub: "{{ ansible_facts['default_ipv4']['interface']}}"

- name: Add nat-table.nft
  template: 
    src: nat_table.j2
    dest: /etc/nftables.d/nat-table.nft
    force: true
    mode: '0644'

- name: Replace current nftables.conf
  copy:
    src: nftables.conf
    dest: /etc/nftables.conf
    force: true
    mode: '0644'

- name: Apply new nftables rules
  command: 'nft -f /etc/nftables.conf'

- name: Restart tinc
  systemd:
    name: tinc@{{ vpn_name }}
    state: restarted
